spring:
  mail:
    host: smtp.gmail.com
    password: Pinsu@012
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    username: ujjawalkinkg@gmail.com
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    url: jdbc:mysql://jrtp.chrojop7exng.ap-south-1.rds.amazonaws.com:3306/jrtp
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true